### ISSUE TITLE
unable to open database file: /data/state.db on starting podman container

### ISSUE THREAD

**Issue by GrassBlock1** [matze/wastebin#74]
Hello.
I built a podman image with `podman build` to run wastebin on a arm64 machine with no errors, and wrote a `compose.yml`:
```yaml
version: '3.3'
services:
  wastebin:
    container_name: "wastebin_0"
    environment:
      - WASTEBIN_DATABASE_PATH=/data/state.db
      - WASTEBIN_PASSWORD_SALT=9<random>kfv
      - WASTEBIN_SIGNING_KEY=9<random>s
      - WASTEBIN_TITLE=wasteb1n
    ports:
      - "127.0.0.1:8088:8088"
    volumes:
      - './data:/data'
    image: "localhost/wastebin:v2.5.0"
```
But when I tried to run the container with `podman-compose` it shows the following error:
`Error: sqlite error: unable to open database file: /data/state.db`

and I tried solution within #56 but still get this error and nothing appears in my `data` folder:
![image](https://github.com/user-attachments/assets/26f792da-1b39-40b5-8331-5b92a95bb851)

I don't know how this happened so I need some help. Thanks in advance.
